import type {Metadata} from 'next'
import {Varela_Round} from 'next/font/google'
import './globals.css'
import clsx from 'clsx'

const varelaRound = Varela_Round({subsets: ['latin'], weight: '400'})

export const metadata: Metadata = {
  title: 'Squarespace Portfolio Clone | Bertie Gregory',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={clsx(varelaRound.className, 'container border-2 min-h-screen')}>
        {children}
      </body>
    </html>
  )
}
